#!/bin/bash

# check if docker image is available
imgtst=$(/usr/bin/docker image inspect quartz | wc)
if [ $? -ne 0 ]; then
  echo "$0: unable to find quartz docker image" 2>&1
  exit -1
fi

# check for quartz config
cfgfile=""
if [ -f ./.quartz/quartz.config.ts ]; then
  cfgfile="-v./.quartz/quartz.config.ts:/usr/src/app/quartz.config.ts"
fi

# check for quartz layout
lytfile=""
if [ -f ./.quartz/quartz.layout.ts ]; then
  lytfile="-v./.quartz/quartz.layout.ts:/usr/src/app/quartz.layout.ts"
fi

# check for quartz css
cssfile=""
if [ -f ./.quartz/custom.scss ]; then
   cssfile="-v./.quartz/custom.scss:/usr/src/app/quartz/styles/custom.scss"
fi

if [ -d output/ ]; then
    rm -rf output/*
else
    mkdir -p output
fi

/usr/bin/docker run --name quartzcmd -v.:/usr/src/app/content $cfgfile $lytfile $cssfile -itp 8080:8080 quartz $@

# copy build output
/usr/bin/docker cp quartzcmd:/usr/src/app/public/. output
/usr/bin/docker rm quartzcmd >/dev/null
